// This file provides a client with methods as well as functions to interact with the HTTP API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package gopkgsite

import (
	"context"
	"encoding/json/v2"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/go-api-libs/api"
)

const defaultUserAgent = "Go Pkgsite API"

var defaultBaseURL = &url.URL{
	Scheme: "https",
	Host:   "pkg.go.dev",
	Path:   "/v1beta",
}

// Client is an HTTP client for the gopkgsite API.
type Client struct {
	// The HTTP client to use for requests.
	cli *http.Client
	// The base URL
	baseURL *url.URL
	// The user agent
	userAgent string
}

// ClientOption configures a [Client].
type ClientOption func(*Client)

// WithBaseURL returns a [ClientOption] that overrides the default base URL.
// It will prefix a leading slash to the path if there is none.
func WithBaseURL(baseURL *url.URL) ClientOption {
	if !strings.HasPrefix(baseURL.Path, "/") {
		baseURL.Path = "/" + baseURL.Path
	}

	return func(c *Client) { c.baseURL = baseURL }
}

// WithHTTPClient returns a [ClientOption] that sets a custom HTTP client.
func WithHTTPClient(cli *http.Client) ClientOption {
	return func(c *Client) { c.cli = cli }
}

// NewClient creates a new Client.
func NewClient(opts ...ClientOption) (*Client, error) {
	c := &Client{
		cli:       http.DefaultClient,
		baseURL:   defaultBaseURL,
		userAgent: defaultUserAgent,
	}

	for _, opt := range opts {
		opt(c)
	}

	return c, nil
}

// Paths of packages importing the package at {path},
// not including packages in the same module.
// Filtering is applied to the list of paths in the response.
// Only paths that match the filter query parameter are returned.
// Within a filter, the variable `path` is set to the import path.
//
//	GET /imported-by/{path}
func (c *Client) GetImportedBy(ctx context.Context, path string, params *GetImportedByParams) (*PackageImportedBy, error) {
	return GetImportedBy[PackageImportedBy](ctx, c, path, params)
}

// Paths of packages importing the package at {path},
// not including packages in the same module.
// Filtering is applied to the list of paths in the response.
// Only paths that match the filter query parameter are returned.
// Within a filter, the variable `path` is set to the import path.
// You can define a custom result to unmarshal the response into.
//
//	GET /imported-by/{path}
func GetImportedBy[R any](ctx context.Context, c *Client, path string, params *GetImportedByParams) (*R, error) {
	u := c.baseURL.JoinPath("imported-by", path)

	if params != nil {
		q := make(url.Values, 5)

		if params.Module != "" {
			q["module"] = []string{params.Module}
		}

		if params.Version != "" {
			q["version"] = []string{params.Version}
		}

		if params.Limit != 0 {
			q["limit"] = []string{strconv.Itoa(params.Limit)}
		}

		if params.Token != "" {
			q["token"] = []string{params.Token}
		}

		if params.Filter != "" {
			q["filter"] = []string{params.Filter}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Successful response
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Information about the module at {path}.
//
//	GET /module/{path}
func (c *Client) GetModule(ctx context.Context, path string, params *GetModuleParams) (*Module, error) {
	return GetModule[Module](ctx, c, path, params)
}

// Information about the module at {path}.
// You can define a custom result to unmarshal the response into.
//
//	GET /module/{path}
func GetModule[R any](ctx context.Context, c *Client, path string, params *GetModuleParams) (*R, error) {
	u := c.baseURL.JoinPath("module", path)

	if params != nil {
		q := make(url.Values, 3)

		if params.Version != "" {
			q["version"] = []string{params.Version}
		}

		if params.Licenses {
			q["licenses"] = []string{strconv.FormatBool(params.Licenses)}
		}

		if params.Readme {
			q["readme"] = []string{strconv.FormatBool(params.Readme)}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Successful response
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Information about the package at {path}.
//
//	GET /package/{path}
func (c *Client) GetPackage(ctx context.Context, path string, params *GetPackageParams) (*Package, error) {
	return GetPackage[Package](ctx, c, path, params)
}

// Information about the package at {path}.
// You can define a custom result to unmarshal the response into.
//
//	GET /package/{path}
func GetPackage[R any](ctx context.Context, c *Client, path string, params *GetPackageParams) (*R, error) {
	u := c.baseURL.JoinPath("package", path)

	if params != nil {
		q := make(url.Values, 8)

		if params.Module != "" {
			q["module"] = []string{params.Module}
		}

		if params.Version != "" {
			q["version"] = []string{params.Version}
		}

		if params.Goos != "" {
			q["goos"] = []string{params.Goos}
		}

		if params.Goarch != "" {
			q["goarch"] = []string{params.Goarch}
		}

		if params.Doc != "" {
			q["doc"] = []string{params.Doc}
		}

		if params.Examples {
			q["examples"] = []string{strconv.FormatBool(params.Examples)}
		}

		if params.Imports {
			q["imports"] = []string{strconv.FormatBool(params.Imports)}
		}

		if params.Licenses {
			q["licenses"] = []string{strconv.FormatBool(params.Licenses)}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Successful response
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Information about packages of the module at {path}.
// Filtering is applied to the list of packages in the response.
// Only packages that match the filter query parameter are returned.
//
//	GET /packages/{path}
func (c *Client) GetPackages(ctx context.Context, path string, params *GetPackagesParams) (*PackagesResponse, error) {
	return GetPackages[PackagesResponse](ctx, c, path, params)
}

// Information about packages of the module at {path}.
// Filtering is applied to the list of packages in the response.
// Only packages that match the filter query parameter are returned.
// You can define a custom result to unmarshal the response into.
//
//	GET /packages/{path}
func GetPackages[R any](ctx context.Context, c *Client, path string, params *GetPackagesParams) (*R, error) {
	u := c.baseURL.JoinPath("packages", path)

	if params != nil {
		q := make(url.Values, 4)

		if params.Version != "" {
			q["version"] = []string{params.Version}
		}

		if params.Limit != 0 {
			q["limit"] = []string{strconv.Itoa(params.Limit)}
		}

		if params.Token != "" {
			q["token"] = []string{params.Token}
		}

		if params.Filter != "" {
			q["filter"] = []string{params.Filter}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Successful response
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Search results. Only results that match the filter query parameter are returned.
//
//	GET /search
func (c *Client) GetSearch(ctx context.Context, params *GetSearchParams) (*PaginatedResponse, error) {
	return GetSearch[PaginatedResponse](ctx, c, params)
}

// Search results. Only results that match the filter query parameter are returned.
// You can define a custom result to unmarshal the response into.
//
//	GET /search
func GetSearch[R any](ctx context.Context, c *Client, params *GetSearchParams) (*R, error) {
	u := c.baseURL.JoinPath("search")

	if params != nil {
		q := make(url.Values, 5)

		if params.Q != "" {
			q["q"] = []string{params.Q}
		}

		if params.Symbol != "" {
			q["symbol"] = []string{params.Symbol}
		}

		if params.Limit != 0 {
			q["limit"] = []string{strconv.Itoa(params.Limit)}
		}

		if params.Token != "" {
			q["token"] = []string{params.Token}
		}

		if params.Filter != "" {
			q["filter"] = []string{params.Filter}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Successful response
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// List of symbols for the package at {path}.
// Filtering is applied to the list of symbols in the response.
// Only symbols that match the filter query parameter are returned.
//
//	GET /symbols/{path}
func (c *Client) GetSymbols(ctx context.Context, path string, params *GetSymbolsParams) (*PackageSymbols, error) {
	return GetSymbols[PackageSymbols](ctx, c, path, params)
}

// List of symbols for the package at {path}.
// Filtering is applied to the list of symbols in the response.
// Only symbols that match the filter query parameter are returned.
// You can define a custom result to unmarshal the response into.
//
//	GET /symbols/{path}
func GetSymbols[R any](ctx context.Context, c *Client, path string, params *GetSymbolsParams) (*R, error) {
	u := c.baseURL.JoinPath("symbols", path)

	if params != nil {
		q := make(url.Values, 7)

		if params.Module != "" {
			q["module"] = []string{params.Module}
		}

		if params.Version != "" {
			q["version"] = []string{params.Version}
		}

		if params.Goos != "" {
			q["goos"] = []string{params.Goos}
		}

		if params.Goarch != "" {
			q["goarch"] = []string{params.Goarch}
		}

		if params.Limit != 0 {
			q["limit"] = []string{strconv.Itoa(params.Limit)}
		}

		if params.Token != "" {
			q["token"] = []string{params.Token}
		}

		if params.Filter != "" {
			q["filter"] = []string{params.Filter}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Successful response
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Versions of the module at {path}.
// If there are tagged versions, they are returned.
// Otherwise, the 10 most recent pseudo-versions are returned.
// The versions are in descending order.
// Only results that match the filter query parameter are returned.
//
//	GET /versions/{path}
func (c *Client) GetVersions(ctx context.Context, path string, params *GetVersionsParams) (*PaginatedResponse, error) {
	return GetVersions[PaginatedResponse](ctx, c, path, params)
}

// Versions of the module at {path}.
// If there are tagged versions, they are returned.
// Otherwise, the 10 most recent pseudo-versions are returned.
// The versions are in descending order.
// Only results that match the filter query parameter are returned.
// You can define a custom result to unmarshal the response into.
//
//	GET /versions/{path}
func GetVersions[R any](ctx context.Context, c *Client, path string, params *GetVersionsParams) (*R, error) {
	u := c.baseURL.JoinPath("versions", path)

	if params != nil {
		q := make(url.Values, 3)

		if params.Limit != 0 {
			q["limit"] = []string{strconv.Itoa(params.Limit)}
		}

		if params.Token != "" {
			q["token"] = []string{params.Token}
		}

		if params.Filter != "" {
			q["filter"] = []string{params.Filter}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Successful response
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Vulnerabilities of the module or package at {path}, from
// the Go vulnerability database (https://vuln.go.dev).
// Only results that match the filter query parameter are returned.
//
//	GET /vulns/{path}
func (c *Client) GetVulns(ctx context.Context, path string, params *GetVulnsParams) (*PaginatedResponse, error) {
	return GetVulns[PaginatedResponse](ctx, c, path, params)
}

// Vulnerabilities of the module or package at {path}, from
// the Go vulnerability database (https://vuln.go.dev).
// Only results that match the filter query parameter are returned.
// You can define a custom result to unmarshal the response into.
//
//	GET /vulns/{path}
func GetVulns[R any](ctx context.Context, c *Client, path string, params *GetVulnsParams) (*R, error) {
	u := c.baseURL.JoinPath("vulns", path)

	if params != nil {
		q := make(url.Values, 5)

		if params.Module != "" {
			q["module"] = []string{params.Module}
		}

		if params.Version != "" {
			q["version"] = []string{params.Version}
		}

		if params.Limit != 0 {
			q["limit"] = []string{strconv.Itoa(params.Limit)}
		}

		if params.Token != "" {
			q["token"] = []string{params.Token}
		}

		if params.Filter != "" {
			q["filter"] = []string{params.Filter}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Successful response
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}
