// This file provides tests for the client.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package gopkgsite

import (
	"encoding/json/jsontext"
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"testing"

	"github.com/go-api-libs/api"
)

func newTestServer(t *testing.T, status int) *httptest.Server {
	t.Helper()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(status)
	}))
	t.Cleanup(srv.Close)
	return srv
}

type roundTripFunc func(*http.Request) (*http.Response, error)

func (f roundTripFunc) RoundTrip(r *http.Request) (*http.Response, error) {
	return f(r)
}

func TestClient_Error(t *testing.T) {
	t.Run("GetImportedBy", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetImportedBy(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetImportedBy(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetImportedBy(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetModule", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetModule(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetModule(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetModule(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetPackage", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetPackage(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetPackage(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetPackage(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetPackages", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetPackages(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetPackages(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetPackages(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetSearch", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetSearch(t.Context(), nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetSearch(t.Context(), nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetSearch(t.Context(), nil); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetSymbols", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetSymbols(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetSymbols(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetSymbols(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetVersions", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetVersions(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetVersions(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetVersions(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetVulns", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetVulns(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetVulns(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetVulns(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})
}
