// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package gopkgsite

import (
	"encoding/json/v2"
	"time"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
)

// GetImportedByParams holds the query parameters for GetImportedBy.
type GetImportedByParams struct {
	// Module path.
	Module string
	// Module version: semantic version, 'latest', or default branches 'master' or 'main'.
	// (Latest if empty).
	Version string
	// Max number of items to return.
	Limit int
	// Where to resume listing.
	Token string
	// Include only items matching the regular expression filter.
	Filter string
}

// GetModuleParams holds the query parameters for GetModule.
type GetModuleParams struct {
	// Module version: semantic version, 'latest', or default branches 'master' or 'main'.
	// (Latest if empty).
	Version string
	// Whether to include licenses in the result.
	Licenses bool
	// Whether to include the README in the result.
	Readme bool
}

// GetPackageParams holds the query parameters for GetPackage.
type GetPackageParams struct {
	// Module path.
	Module string
	// Module version: semantic version, 'latest', or default branches 'master' or 'main'.
	// (Latest if empty).
	Version string
	// GOOS of documentation build context.
	Goos string
	// GOARCH of documentation build context.
	Goarch string
	// Documentation format: text, html, md or markdown.
	// If omitted, documentation is not returned.
	Doc string
	// Whether to include examples with the returned documentation.
	Examples bool
	// Whether to include the packages that this one imports.
	Imports bool
	// Whether to include licenses in the result.
	Licenses bool
}

// GetPackagesParams holds the query parameters for GetPackages.
type GetPackagesParams struct {
	// Module version: semantic version, 'latest', or default branches 'master' or 'main'.
	// (Latest if empty).
	Version string
	// Max number of items to return.
	Limit int
	// Where to resume listing.
	Token string
	// Include only items matching the regular expression filter.
	Filter string
}

// GetSearchParams holds the query parameters for GetSearch.
type GetSearchParams struct {
	// Find packages matching this query.
	Q string
	// If non-empty, find symbols matching this string.
	// The query further restricts the search to matching packages.
	Symbol string
	// Max number of items to return.
	Limit int
	// Where to resume listing.
	Token string
	// Include only items matching the regular expression filter.
	Filter string
}

// GetSymbolsParams holds the query parameters for GetSymbols.
type GetSymbolsParams struct {
	// Module path.
	Module string
	// Module version: semantic version, 'latest', or default branches 'master' or 'main'.
	// (Latest if empty).
	Version string
	// GOOS of documentation build context.
	Goos string
	// GOARCH of documentation build context.
	Goarch string
	// Max number of items to return.
	Limit int
	// Where to resume listing.
	Token string
	// Include only items matching the regular expression filter.
	Filter string
}

// GetVersionsParams holds the query parameters for GetVersions.
type GetVersionsParams struct {
	// Max number of items to return.
	Limit int
	// Where to resume listing.
	Token string
	// Include only items matching the regular expression filter.
	Filter string
	// Whether to include pseudo-versions in the result.
	Pseudo bool
}

// GetVulnsParams holds the query parameters for GetVulns.
type GetVulnsParams struct {
	// Module path.
	Module string
	// Module version: semantic version, 'latest', or default branches 'master' or 'main'.
	// (Latest if empty).
	Version string
	// Max number of items to return.
	Limit int
	// Where to resume listing.
	Token string
	// Include only items matching the regular expression filter.
	Filter string
}

// Candidate defines a model
type Candidate struct {
	ModulePath  string `json:"modulePath,omitzero"`
	PackagePath string `json:"packagePath,omitzero"`
}

// Candidates defines a model
type Candidates []Candidate

// Error defines a model
type Error struct {
	Candidates Candidates `json:"candidates,omitzero"`
	// Code is the HTTP status code.
	Code int `json:"code"`
	// Fixes are suggestions for how to fix.
	Fixes   []string `json:"fixes,omitzero"`
	Message string   `json:"message,omitzero"`
}

// License defines a model
type License struct {
	Contents string   `json:"contents,omitzero"`
	FilePath string   `json:"filePath,omitzero"`
	Types    []string `json:"types,omitzero"`
}

// Licenses defines a model
type Licenses []License

// Module defines a model
type Module struct {
	// CommitTime is the timestamp returned by the module proxy's .info endpoint,
	// representing the time the version was created.
	CommitTime        time.Time `json:"commitTime,omitempty"`
	GoModContents     string    `json:"goModContents,omitzero"`
	HasGoMod          bool      `json:"hasGoMod,omitempty"`
	IsLatest          bool      `json:"isLatest,omitempty"`
	IsRedistributable bool      `json:"isRedistributable,omitempty"`
	IsStandardLibrary bool      `json:"isStandardLibrary,omitempty"`
	Licenses          Licenses  `json:"licenses,omitzero"`
	Path              string    `json:"path,omitzero"`
	Readme            *Readme   `json:"readme,omitempty"`
	RepoURL           string    `json:"repoUrl,omitzero"`
	Version           string    `json:"version,omitzero"`
}

// ModuleVersion defines a model
type ModuleVersion struct {
	CommitTime        time.Time `json:"commitTime,omitempty"`
	Deprecated        bool      `json:"deprecated,omitempty"`
	DeprecationReason string    `json:"deprecationReason,omitzero"`
	// HasGoMod is whether the module has a go.mod file.
	HasGoMod bool `json:"hasGoMod,omitempty"`
	// IsRedistributable is whether the license allows distribution.
	IsRedistributable bool `json:"isRedistributable,omitempty"`
	// LatestVersion is the latest unretracted version.
	LatestVersion    string `json:"latestVersion,omitzero"`
	ModulePath       string `json:"modulePath,omitzero"`
	Retracted        bool   `json:"retracted,omitempty"`
	RetractionReason string `json:"retractionReason,omitzero"`
	Version          string `json:"version,omitzero"`
}

// ModuleVersions defines a model
type ModuleVersions []ModuleVersion

// Package defines a model
type Package struct {
	Docs     string   `json:"docs,omitzero"`
	Goarch   string   `json:"goarch,omitzero"`
	Goos     string   `json:"goos,omitzero"`
	Imports  []string `json:"imports,omitzero"`
	IsLatest bool     `json:"isLatest,omitempty"`
	// IsRedistributable is whether the license allows distribution.
	IsRedistributable bool     `json:"isRedistributable,omitempty"`
	IsStandardLibrary bool     `json:"isStandardLibrary,omitempty"`
	Licenses          Licenses `json:"licenses,omitzero"`
	ModulePath        string   `json:"modulePath,omitzero"`
	Name              string   `json:"name,omitzero"`
	Path              string   `json:"path,omitzero"`
	Synopsis          string   `json:"synopsis,omitzero"`
	Version           string   `json:"version,omitzero"`
}

// PackageImportedBy defines a model
type PackageImportedBy struct {
	ImportedBy *PaginatedResponse_string `json:"importedBy,omitempty"`
	ModulePath string                    `json:"modulePath,omitzero"`
	Version    string                    `json:"version,omitzero"`
}

// PackageInfo defines a model
type PackageInfo struct {
	// IsRedistributable is whether the license allows distribution.
	IsRedistributable bool   `json:"isRedistributable,omitempty"`
	Name              string `json:"name,omitzero"`
	Path              string `json:"path,omitzero"`
	Synopsis          string `json:"synopsis,omitzero"`
}

// PackageInfos defines a model
type PackageInfos []PackageInfo

// PackageSymbols defines a model
type PackageSymbols struct {
	ModulePath string                    `json:"modulePath,omitzero"`
	Symbols    *PaginatedResponse_Symbol `json:"symbols,omitempty"`
	Version    string                    `json:"version,omitzero"`
}

// PackagesResponse defines a model
type PackagesResponse struct {
	IsStandardLibrary bool                           `json:"isStandardLibrary,omitempty"`
	ModulePath        string                         `json:"modulePath,omitzero"`
	Packages          *PaginatedResponse_PackageInfo `json:"packages,omitempty"`
	Version           string                         `json:"version,omitzero"`
}

// PaginatedResponse_ModuleVersion defines a model
type PaginatedResponse_ModuleVersion struct {
	Items         ModuleVersions `json:"items,omitzero"`
	NextPageToken string         `json:"nextPageToken,omitzero"`
	Total         *int           `json:"total,omitempty"`
}

// PaginatedResponse_PackageInfo defines a model
type PaginatedResponse_PackageInfo struct {
	Items         PackageInfos `json:"items,omitzero"`
	NextPageToken string       `json:"nextPageToken,omitzero"`
	Total         *int         `json:"total,omitempty"`
}

// PaginatedResponse_SearchResult defines a model
type PaginatedResponse_SearchResult struct {
	Items         SearchResults `json:"items,omitzero"`
	NextPageToken string        `json:"nextPageToken,omitzero"`
	Total         *int          `json:"total,omitempty"`
}

// PaginatedResponse_Symbol defines a model
type PaginatedResponse_Symbol struct {
	Items         Symbols `json:"items,omitzero"`
	NextPageToken string  `json:"nextPageToken,omitzero"`
	Total         *int    `json:"total,omitempty"`
}

// PaginatedResponse_Vulnerability defines a model
type PaginatedResponse_Vulnerability struct {
	Items         Vulnerabilities `json:"items,omitzero"`
	NextPageToken string          `json:"nextPageToken,omitzero"`
	Total         *int            `json:"total,omitempty"`
}

// PaginatedResponse_string defines a model
type PaginatedResponse_string struct {
	Items         []string `json:"items,omitzero"`
	NextPageToken string   `json:"nextPageToken,omitzero"`
	Total         *int     `json:"total,omitempty"`
}

// Readme defines a model
type Readme struct {
	Contents string `json:"contents,omitzero"`
	Filepath string `json:"filepath,omitzero"`
}

// SearchResult defines a model
type SearchResult struct {
	ModulePath  string `json:"modulePath,omitzero"`
	PackagePath string `json:"packagePath,omitzero"`
	Synopsis    string `json:"synopsis,omitzero"`
	Version     string `json:"version,omitzero"`
}

// SearchResults defines a model
type SearchResults []SearchResult

// Symbol defines a model
type Symbol struct {
	// Kind is one of "Constant", "Variable", "Function", "Type", "Field", or "Method".
	Kind     string `json:"kind,omitzero"`
	Name     string `json:"name,omitzero"`
	Parent   string `json:"parent,omitzero"`
	Synopsis string `json:"synopsis,omitzero"`
}

// Symbols defines a model
type Symbols []Symbol

// Vulnerabilities defines a model
type Vulnerabilities []Vulnerability

// Vulnerability defines a model
type Vulnerability struct {
	Details      string `json:"details,omitzero"`
	FixedVersion string `json:"fixedVersion,omitzero"`
	ID           string `json:"id,omitzero"`
	Summary      string `json:"summary,omitzero"`
}
