// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package gopkgsite

import (
	"encoding/json/v2"
	"time"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
)

// GetImportedByParams holds the query parameters for GetImportedBy.
type GetImportedByParams struct {
	// Module path.
	Module string
	// Module version: semantic version, 'latest', or default branches 'master' or 'main'.
	// (Latest if empty).
	Version string
	// Max number of items to return.
	Limit int
	// Where to resume listing.
	Token string
	// Include only items matching the regular expression filter.
	Filter string
}

// GetModuleParams holds the query parameters for GetModule.
type GetModuleParams struct {
	// Module version: semantic version, 'latest', or default branches 'master' or 'main'.
	// (Latest if empty).
	Version string
	// Whether to include licenses in the result.
	Licenses bool
	// Whether to include the README in the result.
	Readme bool
}

// GetPackageParams holds the query parameters for GetPackage.
type GetPackageParams struct {
	// Module path.
	Module string
	// Module version: semantic version, 'latest', or default branches 'master' or 'main'.
	// (Latest if empty).
	Version string
	// GOOS of documentation build context.
	Goos string
	// GOARCH of documentation build context.
	Goarch string
	// Documentation format: text, html, md or markdown.
	// If omitted, documentation is not returned.
	Doc string
	// Whether to include examples with the returned documentation.
	Examples bool
	// Whether to include the packages that this one imports.
	Imports bool
	// Whether to include licenses in the result.
	Licenses bool
}

// GetPackagesParams holds the query parameters for GetPackages.
type GetPackagesParams struct {
	// Module version: semantic version, 'latest', or default branches 'master' or 'main'.
	// (Latest if empty).
	Version string
	// Max number of items to return.
	Limit int
	// Where to resume listing.
	Token string
	// Include only items matching the regular expression filter.
	Filter string
}

// GetSearchParams holds the query parameters for GetSearch.
type GetSearchParams struct {
	// Find packages matching this query.
	Q string
	// If non-empty, find symbols matching this string.
	// The query further restricts the search to matching packages.
	Symbol string
	// Max number of items to return.
	Limit int
	// Where to resume listing.
	Token string
	// Include only items matching the regular expression filter.
	Filter string
}

// GetSymbolsParams holds the query parameters for GetSymbols.
type GetSymbolsParams struct {
	// Module path.
	Module string
	// Module version: semantic version, 'latest', or default branches 'master' or 'main'.
	// (Latest if empty).
	Version string
	// GOOS of documentation build context.
	Goos string
	// GOARCH of documentation build context.
	Goarch string
	// Max number of items to return.
	Limit int
	// Where to resume listing.
	Token string
	// Include only items matching the regular expression filter.
	Filter string
}

// GetVersionsParams holds the query parameters for GetVersions.
type GetVersionsParams struct {
	// Max number of items to return.
	Limit int
	// Where to resume listing.
	Token string
	// Include only items matching the regular expression filter.
	Filter string
}

// GetVulnsParams holds the query parameters for GetVulns.
type GetVulnsParams struct {
	// Module path.
	Module string
	// Module version: semantic version, 'latest', or default branches 'master' or 'main'.
	// (Latest if empty).
	Version string
	// Max number of items to return.
	Limit int
	// Where to resume listing.
	Token string
	// Include only items matching the regular expression filter.
	Filter string
}

// Candidate defines a model
type Candidate struct {
	ModulePath  string `json:"modulePath,omitzero"`
	PackagePath string `json:"packagePath,omitzero"`
}

// Error defines a model
type Error struct {
	Candidates ErrorCandidates `json:"candidates,omitempty"`
	// HTTP status code
	Code *int `json:"code,omitempty"`
	// Unexported field for internal tracking
	Err *Error `json:"err,omitempty"`
	// suggestions for how to fix
	Fixes   []string `json:"fixes,omitempty"`
	Message string   `json:"message,omitzero"`
}

// ErrorCandidates defines a model
type ErrorCandidates []Candidate

// License defines a model
type License struct {
	Contents string   `json:"contents,omitzero"`
	FilePath string   `json:"filePath,omitzero"`
	Types    []string `json:"types,omitempty"`
}

// Module defines a model
type Module struct {
	// CommitTime is the timestamp returned by the module proxy's .info endpoint,
	// representing the time the version was created.
	CommitTime        time.Time      `json:"commitTime,omitempty"`
	GoModContents     string         `json:"goModContents,omitzero"`
	HasGoMod          bool           `json:"hasGoMod,omitempty"`
	IsLatest          bool           `json:"isLatest,omitempty"`
	IsRedistributable bool           `json:"isRedistributable,omitempty"`
	IsStandardLibrary bool           `json:"isStandardLibrary,omitempty"`
	Licenses          ModuleLicenses `json:"licenses,omitempty"`
	Path              string         `json:"path,omitzero"`
	Readme            *Readme        `json:"readme,omitempty"`
	RepoURL           string         `json:"repoUrl,omitzero"`
	Version           string         `json:"version,omitzero"`
}

// ModuleLicenses defines a model
type ModuleLicenses []License

// ModuleVersion defines a model
type ModuleVersion struct {
	CommitTime        time.Time `json:"commitTime,omitempty"`
	Deprecated        bool      `json:"deprecated,omitempty"`
	DeprecationReason string    `json:"deprecationReason,omitzero"`
	// Whether the module has a go.mod file.
	HasGoMod bool `json:"hasGoMod,omitempty"`
	// Whether the license allows distribution.
	IsRedistributable bool `json:"isRedistributable,omitempty"`
	// latest unretracted version
	LatestVersion    string `json:"latestVersion,omitzero"`
	ModulePath       string `json:"modulePath,omitzero"`
	Retracted        bool   `json:"retracted,omitempty"`
	RetractionReason string `json:"retractionReason,omitzero"`
	Version          string `json:"version,omitzero"`
}

// Package defines a model
type Package struct {
	Docs              string         `json:"docs,omitzero"`
	Goarch            string         `json:"goarch,omitzero"`
	Goos              string         `json:"goos,omitzero"`
	Imports           []string       `json:"imports,omitempty"`
	IsLatest          bool           `json:"isLatest,omitempty"`
	IsStandardLibrary bool           `json:"isStandardLibrary,omitempty"`
	Licenses          ModuleLicenses `json:"licenses,omitempty"`
	ModulePath        string         `json:"modulePath,omitzero"`
	Version           string         `json:"version,omitzero"`
}

// PackageImportedBy defines a model
type PackageImportedBy struct {
	ImportedBy *PaginatedResponse `json:"importedBy,omitempty"`
	ModulePath string             `json:"modulePath,omitzero"`
	Version    string             `json:"version,omitzero"`
}

// PackageInfo defines a model
type PackageInfo struct {
	// Whether the license allows distribution.
	IsRedistributable bool   `json:"isRedistributable,omitempty"`
	Name              string `json:"name,omitzero"`
	Path              string `json:"path,omitzero"`
	Synopsis          string `json:"synopsis,omitzero"`
}

// PackageSymbols defines a model
type PackageSymbols struct {
	ModulePath string             `json:"modulePath,omitzero"`
	Symbols    *PaginatedResponse `json:"symbols,omitempty"`
	Version    string             `json:"version,omitzero"`
}

// PackagesResponse defines a model
type PackagesResponse struct {
	IsStandardLibrary bool               `json:"isStandardLibrary,omitempty"`
	ModulePath        string             `json:"modulePath,omitzero"`
	Packages          *PaginatedResponse `json:"packages,omitempty"`
	Version           string             `json:"version,omitzero"`
}

// PaginatedResponse defines a model
type PaginatedResponse struct {
	Items         []struct{} `json:"items,omitempty"`
	NextPageToken string     `json:"nextPageToken,omitzero"`
	Total         *int       `json:"total,omitempty"`
}

// Readme defines a model
type Readme struct {
	Contents string `json:"contents,omitzero"`
	Filepath string `json:"filepath,omitzero"`
}

// SearchResult defines a model
type SearchResult struct {
	ModulePath  string `json:"modulePath,omitzero"`
	PackagePath string `json:"packagePath,omitzero"`
	Synopsis    string `json:"synopsis,omitzero"`
	Version     string `json:"version,omitzero"`
}

// Symbol defines a model
type Symbol struct {
	Kind     string `json:"kind,omitzero"`
	Name     string `json:"name,omitzero"`
	Parent   string `json:"parent,omitzero"`
	Synopsis string `json:"synopsis,omitzero"`
}

// Vulnerability defines a model
type Vulnerability struct {
	Details      string `json:"details,omitzero"`
	FixedVersion string `json:"fixedVersion,omitzero"`
	ID           string `json:"id,omitzero"`
	Summary      string `json:"summary,omitzero"`
}
